LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

CaseIndentation:
  IndentWhenRelativeTo: end

MethodLength:
  Max: 50

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

AbcSize:
  Enabled: false

TrailingComma:
  EnforcedStyleForMultiline: comma

EmptyLinesAroundBlockBody:
  Enabled: false
